version: '3'
services:
  pgdb:
    image: 'postgres:17.1'
    restart: always
    environment:
      POSTGRES_PASSWORD: simple_pass
      POSTGRES_USER: simple_pg
      POSTGRES_DB: simple_pg_db
    ports:
       - '5432:5432'
  app:
    build:
      context: .
    environment: 
      POSTGRES_PASSWORD: simple_pass
      POSTGRES_USER: simple_pg
      POSTGRES_DB: simple_pg_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: pgdb
    depends_on:
      - pgdb
    ports:
      - '5500:5500'