// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"app/repository"
	"app/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitProductService(db *gorm.DB) service.ProductService {
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	return productService
}
