// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"app/controller"
	"app/repository"
	"app/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitProductApp(db *gorm.DB) controller.ProductController {
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productController := controller.NewProductController(productService)
	return productController
}
